name: Review (elm-review)

on:
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: elm-review
        run: npx elm-review

      - name: 'notify vercel'
        if: always()
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: "Vercel - parked-domain: review"
          github_token: ${{ secrets.GITHUB_TOKEN }}
